kind: PersistentVolume
apiVersion: v1
metadata:
  name: request
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  storageClassName: nfs
  nfs: 
    server: IP
    path: /nfsroot/result
