kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: request-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
